language: node_js
node_js:
  - "node"
  - "12"
before_script:
  - curl -L https://atcoder.jp/users/arkark/history/json -o src/data/atcoder-history.json
script:
  - yarn lint
  - yarn build
cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  target-branch: master
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: develop
    node: "node"
